/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class operasiduaangka extends javax.swing.JPanel {

    /**
     * Creates new form operasiduaangka
     */
    public operasiduaangka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Bil1TextField = new javax.swing.JTextField();
        Bil2TextField = new javax.swing.JTextField();
        HasilTextField = new javax.swing.JTextField();
        TambahButton = new javax.swing.JButton();
        KurangButton = new javax.swing.JButton();
        KaliButton = new javax.swing.JButton();
        BagiButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();

        jLabel1.setText("OPERASI DUA ANGKA");

        jLabel2.setText("bilangan 1");

        jLabel3.setText("bilangan 2");

        jLabel4.setText("hasil");

        Bil1TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bil1TextFieldKeyTyped(evt);
            }
        });

        Bil2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bil2TextFieldKeyTyped(evt);
            }
        });

        HasilTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HasilTextFieldKeyTyped(evt);
            }
        });

        TambahButton.setText("tambah");
        TambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButtonActionPerformed(evt);
            }
        });

        KurangButton.setText("kurang");
        KurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangButtonActionPerformed(evt);
            }
        });

        KaliButton.setText("kali");
        KaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliButtonActionPerformed(evt);
            }
        });

        BagiButton.setText("bagi");
        BagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiButtonActionPerformed(evt);
            }
        });

        jButton5.setText("exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ClearButton.setText("clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Bil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClearButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TambahButton)
                                .addGap(18, 18, 18)
                                .addComponent(KurangButton)
                                .addGap(18, 18, 18)
                                .addComponent(KaliButton)
                                .addGap(18, 18, 18)
                                .addComponent(BagiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bil1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bil2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahButton)
                    .addComponent(KurangButton)
                    .addComponent(KaliButton)
                    .addComponent(BagiButton)
                    .addComponent(jButton5))
                .addGap(56, 56, 56)
                .addComponent(ClearButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlhanan
        Double hasil = bil1 + bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        Bil1TextField.setText("");
        Bil2TextField.setText("");
        HasilTextField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void HasilTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HasilTextFieldKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_HasilTextFieldKeyTyped

    private void Bil1TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bil1TextFieldKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "masukkan hanya angka 0 s/d 9");
            evt.consume();
            
        }
    }//GEN-LAST:event_Bil1TextFieldKeyTyped

    private void Bil2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bil2TextFieldKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "masukkan hanya angka 0 s/d 9");
            evt.consume();
            
        }
    }//GEN-LAST:event_Bil2TextFieldKeyTyped

    private void KurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangButtonActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlhanan
        Double hasil = bil1 - bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_KurangButtonActionPerformed

    private void KaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliButtonActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlhanan
        Double hasil = bil1 *  bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_KaliButtonActionPerformed

    private void BagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiButtonActionPerformed
        // TODO add your handling code here:
        Double bil1 = Double.parseDouble(Bil1TextField.getText());
        Double bil2 = Double.parseDouble(Bil2TextField.getText());
        //proses penjumlhanan
        Double hasil = bil1/bil2;
        //set textnya masuk kedalam textfield
        HasilTextField.setText(Double.toString(hasil));
    }//GEN-LAST:event_BagiButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagiButton;
    private javax.swing.JTextField Bil1TextField;
    private javax.swing.JTextField Bil2TextField;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField HasilTextField;
    private javax.swing.JButton KaliButton;
    private javax.swing.JButton KurangButton;
    private javax.swing.JButton TambahButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
